workflows:
  yetanothernotes-debug-workflow:
    name: YetAnotherNotes Debug Workflow
    max_build_duration: 60
    instance_type: mac_mini
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'feature/*'
          include: true
          source: true
        - pattern: 'bugfix/*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - name: Build debug Android app
        script: ./gradlew assembleDebug
      - name: Test debug Android app
        script: ./gradlew test
        test_report: app/build/test-results/**/*.xml
    artifacts:
      - app/build/outputs/**/**/*.apk
    publishing:
      email:
        recipients:
          - mk.allegro.acc@gmail.com
        notify:
          failure: true

  yetanothernotes-release-workflow:
    name: YetAnotherNotes Release Workflow
    max_build_duration: 60
    instance_type: mac_mini
    environment:
      vars:
        FCI_KEYSTORE_PATH: /tmp/keystore.keystore
        FCI_KEYSTORE: Encrypted(Z0FBQUFBQmdkZ0RBajNicjY0cFFWTlM0bkJZRWtERXVMckZVekF6UTdmMWVTT191NDJJVlAtVHVCYjF2UXNmemIzYUZrQ1kxclNCemJRWGVncldQZE9Lb0VtYU8zZTBUOUdPVUJHNlZvdFBYX2I4Y05kNFVSUzByY3lQdzBiNG5SYlh6Y2p3N1RmUFRlNTRpbnhkNmVTQTBMbTlfY2lmSHlpdTB3TlBZcWtabEZGMFJpMTZNMlJoR0Q0X3NFdUxneTcwdEdOUTRRWlN1NmxHdllwdFpaSHh6UGdiQkU4S3dnbElXNHR2MFhOTUs5M0xFM3JsdTF2Q3ZiZ0tYM1paNUZQcmQ0MjVhSFJJekM3OGpEUkRYSWE5aTlWaDF2VVlPVTlwSzJVd09xMGZBRlRQNTBGWXlsVGpaa2N1aDF2Qzd0NlE5MDhlbHJTT2F3SWxlajRLX0NTSVhXQzBKX1p0UWprekIzYVJROWdCN2Z5b2dDMDJPMFcwY2ExRjhZVU5IZ3JXWkJIb0RxNnFoYmt1ZThlbFAzUkY3d0d4cXRSY1o0UTF0QlM5MEhMNFpUMzZnSEV6SkhfUW11VXhmanVSY0Z4VjdnaFdiRy1GQmFUM0VTcjIybGt2UG5PektDNjdyZi1IRXpPLXZRZmFTQjU3QnZvenlpVFRMbFFBckozOVVra1B1SDd4WEppOXhOUUN1WGg2WnFNbTE0NWZ3Wl9DVTVZcWFPTktpUXdydFA4NDFpMERDOWRkNDltdG9YYjZWQkhWM3ZIQmFtbFN5TkdrSUJYUV9LSlRZSFY1NnR2c0V6RFZRMlFzMVNBOEhyVHBsTi0wN1BneHBpQ2V1Y1BfUll5OU1UazZZR0QzU1FpUkxsaC1XUUtrSThWQ2s0Nk9IdFZUOGpIeHpZM3JGWUxBeko3YmZJZHVQVzJCREZIdTZtc2lxa2FBSWhEeVhkOGN5TENWeFUydnp3ZmJybFdUb19meXFua2xCTl9FYTJJMDVfdlpkY20zRnBOVzlxaWlGQVNZQ2Q0ZnpYUXdsb293LS1FYzlLbGs3SlNmOGZJX0hlU1l1M0RVTWZReF84NENZUUxZSkF4NFIya2c2czM4c0pZdWk1TWRETXhLUWlPNVk1YXp3WmsxNG9hQjB5S0NkaFRIVWxGbjlhZ3Rpcng3NnFXQzBaMmhhWDBUN3JnQWlUdjBMajdOZnpIdGhVRm5qTV9rSDJPTVpMZmI3QWI5UXdJbkRZalppTnZxY1FZMkdjVE1xZ252bDlZSXJpNFFjbmRMYzFNdnVXczY1bHROaTdsaUpTdl9tSFB0VHZYUF80ZDlTOXNNWXJIdG8yRTNqSk55ZU1CZ19FMkZYLW5hSG05QUxPYzdRTEFHOTB5LVFKTHhETW1tWlg4VVhOYklrclJRMHF6aGpoQjJXdzVWX2NUTGFVSzY2bjVtZjNrMnBZa0hMZFI4RXE5MV9kdkRtS2hxcldkWEg2SmxRc3FKXzlIMTdtNUpieTY3Nl9kOVIzN3U1TGNPSElSU0p2RW9mTnRSYkFLNkFOYlllV0hSYkRwRnRIVFRONnQ3N0Y2bzhla2Y1bjNycktzclpJc2QzVmFKUW1LMlBoY1dJclFHY2tMUGRfeTFNNmstMGZ5WjF6Z3pWOGRLdHZyVmZ6dEVRZUFIRXhibzhsRnlnUHVFZ2hkREhZZnFIaTdkOTdYZU9JRWN0VENpUUxBenYtR0I3Mktmc2prdVVDZGp6NnAxSWxyWFNQdnJJOEU4NUljNkFPU0dvZ1R6QXNObjhQelRvcGZ6Z2lPRGtiQmpEOXRmRHozWlZPWEg0aTFEa0ZZcnUyUzFxOGk1aTRvX0tkVzRDMEJiazE1VHFOdXdNOUZlbjQtYmFKNzZlYUpCdjRwbWI2bHU1YlYwV3hwRlBZdWQ2eHRMMU5teVFZd1l1ajBDdjBSNzVXU2hjMmVheU1hWnQ5RDRYUWhyNlBvNjY2U2FFaEdWZ2U3OWlFY3BGMjdOVW5LMklZM3NPdVZxOXB6THl5UWlOVXh6RTlFRm5WTlRGM2ZYTTJsM0ZMczdJVHRQbjFSQmRGUTlDTzFVU255VGF3aEVhc290SlA0M05OX2V5LWVCYVQway1Vc2Z3RUJpcmN3OVZxanh0LUlzdl9MRHlkcHlfdC15X0lrVXNuRkFSd1hMOFhxaHlmS21FcEU1cm9wZEhPcVoxTDRLeE9DZDNENkRmOE9tdDBPZllzOVFXR1EzMXJ1ZVViNFI4dFZLUjZfRHNndnJpRkM5Qnc3bk52d0VTZUZjU2lNZzlmQWl0dnZoZlBtZ1JMQW4tdGtyeFFxY0NsUDZlNGppa3JSR0JjUXJLM1Ruc2dVRklCdmttcUd3bS1CY1hqNmo1dlNRVUVIUU1GUzFENmVtVG12di1VZVZGLVhad1RhRVJWZVRkNV9UdXFVVm13MnJfOENRWE5FMFUtMHIyWGE0WEpldTAwN3R5MUFWZW5xbVRWS0JPVEUzRXNuSjlDWDNreW5BQ1U4YklQcGZTYW5mV0Q0LS1Sd01aM1NFQktUb2tOcEI4czloMmdaZlJuMkVhcDRXRkFJNDV4QlFudGlHQ0JRci1BaUxFQm5Rd3lnbTFxOGpZZkF1d0M3ZzJRV3dRVzl0ZVRnQkJQamFwU1JjUWRuakZoRDR3QnZkTFRReE5KMS1tV1lNbHFGeHBTSlhHSnpZWjVGMHZvZVhyUEF3Q0ZsbmxieVdrMm5XZkFCM1RCUmh0SFJuenBjY0wwWm9pRmx0NllTTXNUWEZmQnN4enZ6SFBlZy1RNkVEeEpsR1Q1ZDZLaGdSckpRYVpYeU53cUFqc0ZObjNyYlhKcWZUUW9LMU5CdlVDemplS1ZvRDhocGpfdnI3UFJ0ZHJ4ZEJKYXF1UFN6dVA5aTcxV0NJMW5KSXZlMUJoQzhMN3BEVzhTV2o4T0drLVpBZXZucTVheV9SVzNlaWVIWnVIMTdKbFVIUExfNUJPMFNzZDJld1ZvNVJJSlpsSEt5X01sUElJNmx4QVd2U2RyMmlvTlNONmp3V3BrbmtONDZUVVZEQ1BXZkFTaEotNnp1aHBxZl80Nmh5T1J1OFp4bFpGc0I0QWJKMjJKMVB6a0s2UDFkeWEtUW5kaWNJSnkzOGlDdDdjclVLdzZFSkJwZ05ySktSQ0xLSkdjby1PV0ljNHNQTzlLUGo1WENoaFVXOHZ2SlQ1TXl6VnRMd29PV1g5VzY1eFczQ3FzaDNTQ1ZsdzNBZ0tUQ3MxaWlJTnhyRmlRTHJqZHhncW9tTTROR0NoMUVfbEp4TUF4SEtQZ3pVM1dJenpJTVhTaFB4eHlEUm0zQTVFU2xyeFZuQ1lpSlZWMFZMWFN0bVZ6S19CVng2eEhQcGlrSVpHWU9RdC1sbTBwZl9POEhubWlsMHVKT0dQaVBLX3FjZ3VhaVlBMzRwdUtZMXFqQzYxOWZvdWNQTkRhNnVab3k5bVFidGF1VDA2bHF3UTV4Q2VEczU4Y2xDSUdyQmdVQVdQSmhETUp2aXhFVkdUU3hlSWpQeDZ2dzFmd2RUMFdaaW9rWmdDWmwySEJWOWMwWERKa1hMX05JRHAyeUZYSzRmTnFPTlEyOEd0XzZER1d4R3pRNDMxZFZDbTFuOHUwaEh3VHR1OE55a2NEWFVGand2eVozSEt0WTNwNnBuV0JyWGg1d1VPeGZDa1lhRkUyLTZZUERnNEM4ak5aVXFNVzY5YXpWQVp0TVZZTkJOd252dTVCeHQwMi11LVB5d0R4VzVvb2Z2czBzR2E2Q2hRX1VjUEN0NnpUMEZMZUNWWnRrN18wQjF2WEJvSm4wYjRpeHNFdXh2NW1Ed0ZCc3pmS3lEVFdpdHVqNkphUEtuaFJBOGd1WnFXemtFOU1YcnNUWW5oaGFEdGpNek50UnJPcWdGQm84RHZGZHdUYmxsdk9ub2hmalgxSC1vcm5sLXAwOGtwVWlBa2Z5M251NW5ybHE2Zk93dlUwbUgyYXNsS1loaDF5TllSRFc3S0N5LVRXUl9haXc2NGVsaXpuLVZzS0Nzd3JFRlJnaUxtNWtRVVpmVzMyOEtKRzZKa3NHaFEzTWE0c2RNZkxBNE9VVmhnZzlINjdIcTM5RnVzeGNYbXRnMk5DemIzX1FzcmN3NVl2dFN4N2stY2QwcnRCMldiYkJSWUVHRWhzV19Bck0wSmlqbDRKcmpCZnIxYWV4c1JOU3d2T21YdTlFZTh3ci1pdDAyUjV3QXZQSEF6Y0NXa0xfU196cWtONVZTakp1TXhieFowQ2xrODVUSnhzcThuS1EyX2JpMjE0X3NEVEtrcEpxdzNuWFRJeWg2MWY5NzBSRFB5RW1Pd3YzeHlvSkhWSTMwMHMtWlVwZUtiYlFDekg3LUhMdFN0Z3pSR1hKV1BFLUNNQkI3ZGZxcjljVGU5V0tmRFgxenk5Wm9xQWpESnZFT1FucUZEYTg5U3h0aFo4VEZnenJzVmdram9yanljSzJxTFBQR1NmazhpOVNXSVVXcUdUYWo2SFk0Zy1sRTgtbHFHYTI3cm9fbS05c3FUb3V3NFkxX3NYT25CZUU3MkpWaFlkM3lOUmxGb1c1OElBaUJIVlROczVncm83ZkpfZHM1aUVJUWtmTzBGMFkzUmVNOF95alQ2Z1ZDVmEwemczb0ZUNnJ5T3ktNlJ3aDFtNVEzd0xacEwzalRCaVF6NDRnQnoxdjBaNC1BOVNySDhxX1ZBOHBGRjVkcXpUV3lYNTVTNmRnUTNEaWN5bGdtLXE4WjJqVWY3ckxTbTRFRGx0bUpmNmFVY2hWZDhZWnNsZmNYSnVfbjdZRjdmbkhrbExpOEFKUzF4dXRlNG9BQldPSEtIaWN6OUktN1Bfb0oyOEpCbm5BUWQ5a0M1Q0U4UEtXMFB2eWlFUVk0aXZITkNsNEJrdGladEM2QV9GYS1EeUNPakdKT1dlSDluNllZUFI2Vkg1TThqdmVOSjAzcmJWY05UM0NOQkx6ZUFUMjJLMnFuOC16d1huT0ZIVHNueHJrVGxGcWJsb3lNTHVJZlMyZ0c1MWFsa3huZmZrZGUtbkN6aFZ5TGlGWVVsRldBY0ZNQXpaYjVUX1lSOVo1QmJBRlZ1QWJqeG9rZHlWdElTZ0RKVjZKU1ZRNjZwMGpubHZnZDRWVW9IZ1k4c191MnBRYU5nU1FEWjFURG9mUFh1bE1fOUdhSFl5SDQ2TVpqZFpRSk1kbzMwUWlabjJpYzBxWXE2SmIyZU5YMGdEcmR0b1RxZXIxMFEzemhGVjNYbHNTTGkzYUhBNnNFaFdrNXdyREQzM2MyRlF3OWQ0V2Z6UTlReEFfUThNTHlJMzdPNWJLTHlGWkhlNnBHWGNnd3Z2SVhFRlNpcHVXMjlTSTVlWTc3bEpNazNsZ1FNbTFmVDZvVVhBc3FYaW5jc0JtQ085UHRZSFFIMlk0dkc2b18wamNhbVVwM3lNb2VZcFBBbGNuVHdMVkN1bGU3NXJkMXBPMmRYdnc9PQ==)
        FCI_KEYSTORE_PASSWORD: Encrypted(Z0FBQUFBQmdkZ0UydkVnaGRVek05akhFSkNTZ0loSmNqNy13MmZEb0xGMjRMdkFodGhScW00UzRXYnh2d2ZDRHpLWExSbXhHYWpNbVNUY2ZhX3AzSmkzU2NFZm1lamp2aVRsdHVacmhkakNnVXFhMWNvdTNLWUk9)
        FCI_KEY_PASSWORD: Encrypted(Z0FBQUFBQmdkZ0ZXb2xzMVlvSkNwX3NpVUJROGktZkcxM1RlX3N2aGxhRGZqakFGdkRjS1VtMWRCTVpmeUdVTFVfeHNFTFE2dXFyVFBnMHkwYXo2UVVtdklIRklsYklBVWpCNmF2NHowUDVUQ0pDOXVOQkRHQ1E9)
        FCI_KEY_ALIAS: Encrypted(Z0FBQUFBQmdkZ0YxLUZWYkJjZTVDYnlwYTAwcEJDSjlFem1IMGRGeUQ3VUoxQ0R1OWd6dkVzT29wYzFzVVpxcm1kNHlaZFJVbHc5dkFYUS1QZ2JQM0hZQU93enNXYWFmaENTT3dFQVNlOWp2eXlfQUxROW5nRHlGS0pxZmFLUVowMjFzZFhIekhweDc=)
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'release/*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - name: Set up local properties
        script: echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/local.properties"
      - name: Set up key.properties
        script: |
          echo $FCI_KEYSTORE | base64 --decode > $FCI_KEYSTORE_PATH
          cat >> "$FCI_BUILD_DIR/android/key.properties" <<EOF
          storePassword=$FCI_KEYSTORE_PASSWORD
          keyPassword=$FCI_KEY_PASSWORD
          keyAlias=$FCI_KEY_ALIAS
          storeFile=$FCI_KEYSTORE_PATH
          EOF
      - name: Build Android app
        script: ./gradlew assembleRelease
      - name: Test Android app
        script: ./gradlew test
        test_report: app/build/test-results/**/*.xml
    artifacts:
      - app/build/outputs/**/**/*.apk
    publishing:
      email:
        recipients:
          - mk.allegro.acc@gmail.com
        notify:
          success: true
          failure: true
